import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  knowledgeSidebar: [
    'intro',
    {
      type: 'category',
      label: '架构设计',
      items: [{ type: 'autogenerated', dirName: 'architecture' }],
    },
    {
      type: 'category',
      label: '地形系统',
      items: [{ type: 'autogenerated', dirName: 'terrain' }],
    },
    {
      type: 'category',
      label: '建筑系统',
      items: [{ type: 'autogenerated', dirName: 'buildings' }],
    },
    {
      type: 'category',
      label: '道路系统',
      items: [{ type: 'autogenerated', dirName: 'roads' }],
    },
    {
      type: 'category',
      label: '流式加载',
      items: [{ type: 'autogenerated', dirName: 'streaming' }],
    },
    {
      type: 'category',
      label: '数据流程',
      items: [{ type: 'autogenerated', dirName: 'data-pipeline' }],
    },
    {
      type: 'category',
      label: '参考资料',
      items: [{ type: 'autogenerated', dirName: 'references' }],
    },
  ],
};

export default sidebars;
